USE [master]
GO

/****** Object:  Database [BTSDemoEncryptedColumn]    Script Date: 13/12/2020 23:18:27 ******/
CREATE DATABASE [BTSDemoEncryptedColumn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BTSDemoEncryptedColumn', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BTSDemoEncryptedColumn.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BTSDemoEncryptedColumn_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BTSDemoEncryptedColumn_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BTSDemoEncryptedColumn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET ARITHABORT OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET RECOVERY FULL 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET  MULTI_USER 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BTSDemoEncryptedColumn] SET  READ_WRITE 
GO


